:linkcss:
:imagesdir: ./images
:stylesdir: stylesheets/
:stylesheet:  colony.css
:data-uri:

= UNIT- IV

== TALA

=== 4.0 OBJECTIVES

 This unit explains the various aspects of Indian Tala System
 Classification of Talas, angas figuring in different talas, 35 Tala scheme will be explained in detail

=== 4.1 INTRODUCTION
The tala system is perhaps the most difficult and complicated branch of South Indian Music. There is no comparision to it in the other musical systems of the world. The time-measures used by all the nations put together will form but a small fraction of the innumerable varieties of rhythm used in South Indian Music. Tala is the measuring rod of musical time.
Takārah śaṅkarah prōkta
Lakārah śaktiruchyate
Śivaśakti samyōgattāla ityabhidīyate
Takara is the bijakshara of shiva ans lakara is of Shakti. The communion of shiva and Shakti gives rise to Tala. Tandava is the cosmic dance of Shiva the masculine dancing while lasya indicates the famine dancing of Goddess Parvati. The first letters of tandava and Lasya gives rise to Tala the binding factor of Nritya and nritta.
Hastadvayasya samyōge viyōge capi vartate
Vyatimān yo daśa prānih sakala tāla sañjakah
The process of unison and separation of the two hands in coordination with the ten elements of musical time constitutes the Tala. Tala is the time binding factor in music. There are numerous talas in music like ragas. Every tala is reckoned with definite angas in a tala.

=== 4.2 SHADANGAS
• The six angas or modes of reckoning musical time. They are known as Shadangas or six angas.
• Each anga has definite akshara kalas with which it is reckoned

[%header,format=csv]
|===
S.No, Name of the Anga, Sign, Number of Aksharas
1, Laghu, I, 3/4/5/7/9
2, Drutham, O, 2
3, Anudrutam, U, 1
4, Guru, 8, 8
5, Plutam, I8, 12
6, Kakapadam, +, 16
|===

Of the Talangas, only 3 are widely in use. They are called Principle Talangas.
Here is the list of Principle Talangas along with their way of counting


1. Anudrutam (U) – One Beat of the Palm on the lap
2. Drutam (O) – One beat + one wave (usi/visarjitam)
3. Laghu (I) – One beat + Count of the fingers

=== 4.3 SAPTA TALAS
• There are seven principle Talas. they are called Suladi Sapta Talas
• They were called so as they first employed in a particular type of composition known as Suladi

[%header,format=csv]
|===
S. No., Name of the Tala, Sign, Akshara Kala
1, Dhruva Tala, IOII, 14
2, Matya Tala, IOI, 10
3, Rupaka Tala, OI, 6
4, Jhampe Tala, I7UO, 10
5, Triputa Tala, I3OO, 7
6, Ata Tala, I5I5OO, 14
7, Eka Tala, I 4

|===

=== 4.4 JATI

Of the Shadangas, only laghu has variations in number of kriyas. There are 5 Jati bedhs for Laghu in a tala.

1. Trisra Jati - 3 Kriyas
2. Chaturasra Jati - 4 Kriyas
3. Kanda Jati - 5 Kriyas
4. Misra Jati - 7 Kriyas
5. Sankeerna Jati - 9 Kriyas


=== 4.5 THE SCHEME OF 35 TALAS

Briefly stated, the 35 talas result by the change of the laghu jati in the sapta talas. Now taking the Eka tala, if the Chaturasra jati laghu is respectively substituted by the Tisra, Khanda, Misra and Sankirna laghus, we get four new varieties of the Eka tala, the aksharakala value of the avarta varying in each case on account of the substitution of the laghus of different magnitudes. Thus the Eka tala on account of the five laghu jatis admits of five varieties. In the same way the other six talas also admit of five varieties each and we thus get in all, the 35 talas from the seven principal talas. There are the 35 Alankaras to illustrate the 35 talas.
For example if you take Rupaka tala

Ex:

1. Trisra Jati Rupaka Thalam – OI3
2.  Chaturasra Jati Rupaka Thalam – OI4
3. Kanda Jati Rupaka Thalam – OI5
4. Misra Jati Rupaka Thalam – OI7
5. Sankeerna Jaati Rupaka Thalam – OI

It should be remembered that the five angas, Anudrutam, Drutam, Guru, Plutam and Kakapadam do not admit of jati bhedas and hence their values remain constant throughout.
The scheme of thirty-five Talas

[%header,format=csv]
|===
S.No., TALA, Tala Sequence No, Their varieties, Technical terms, Signature, Total akshara kalas for an avarta
1, Dhruva, 1, Tisra, Mani, |3 02 |3 |3, 11
1, Dhruva, 2, Chaturasra, Sankīrṇa, |4 02 |4 |4, 14
1, Dhruva, 2,Khanda, Pramāna, |5 02 |5 |5, 17
1, Dhruva, 4,Misra, Pūrṇa, |7 02 |7 |7, 23
1, Dhruva, 5, Sankirna, Bhuvana, |9 02 |9 |9, 29

2, Mathya, 6, Tisra, sāra, |3 02 |3 ,8
2,Mathya, 7, Chaturasra, sama, |4 02 |4, 10
2,Mathya,8, Khanda, Udaya, |5 02 |5, 12
2,Mathya,9, Misra, Udirna, |7 02 |7, 16
2,Mathya,10, Sankirna, Rāva, |9 02 |9, 20

3, Rupaka, 11, Tisra, Chakra, 02 |3, 5
3,Rupaka, 12, Chaturasra, patti, 02 |4, 6
3,Rupaka, 13, Khanda, Rāja, 02 |5, 7
3,Rupaka, 14, Misra, Kula, 02 |7, 9
3,Rupaka, 15, Sankirna, Bindu, 02 |9, 11

4, Jhampe, 16, Tisra, Kadamba, |3 U1 02, 6
4,Jhampe,17, Chaturasra, Madhura, |4 U1 02, 7
4,Jhampe,18, Khanda, Chana, |5 U1 02, 8
4,Jhampe,19, Misra, Sura, |7 U1 02, 10
4,Jhampe,20, Sankirna, Kara, |9 U1 02, 12

5, Triputa, 21, Tisra, Sankha, |3 02 02, 7
5,Triputa,22, Chaturasra, Adi, |4 02 02, 8
5,Triputa,23, Khanda, Dushkara, |5 02 02, 9
5,Triputa,24, Misra, Lila, |7 02 02 ,11
5,Triputa,25, Sankirna, Bhoga, |9 02 02, 13

6, Ata, 26, Tisra, Gupta, |3 |3 02 02, 10
6,Ata,27, Chaturasra, Lekha, |4 |4 02 02, 12
6,Ata,28, Khanda, Vidala, |5 |5 02 02 ,14
6,Ata,29, Misra, Loya, |7 |7 02 02 ,18
6,Ata,30, Sankirna, Dhira, |9 |9 02 02, 22

7, Eka, 31, Tisra, Sudha, |3, 3
7,Eka,32, Chaturasra, Māna, |4, 4
7,Eka,33 ,Khanda, Rata, |5, 5
7,Eka,34, Misra, Rāga, |7, 7
7,Eka,35, Sankirna, Vasu, |9, 9

|===


With the gati bheda these 35 talas become 175 (35x5=175) talas

=== 4.6 TALA DASA PRANAS

All most all ancient treatises on Music carried them chapters on Tala and expounded the importance of laya in Music along with sruti and svara. It is universally accepted that, 'Rhythm' is the basis for all natural phenomena and all world-processes follow the 'Law of Rhythm'.

Aesthetically speaking, a tala by itself has no charm or beauty. Beauty arises only when Music and lyric are incorporated into a tala in a particular manner generating aesthetic effect. Apart from the Musical treatises providing a charm on the Tala subject, there had been works devoted to the topic of Tala.

Tala has been divided into ten aspects each of which has been regarded as its life known as Tala Dasa pranas. They are Kala, Marga, Kriya, Anga, Graha, Jati, Kala, Laya, Yati and Prastara. Among these again the former five pranas have been held more important than the latter five and they are called Mahapranas and Upapranas respectively.
:icons: font
[NOTE]
====
 Kālō Mārgah Kriyāṅgāni Grahō Jātih Kalā Layah |
 Yati Prastārakam cheti Tāla Prāna Dasa śmritah ||
====

==== 4.6.1 KALA

This element is defined as the mode of measuring the duration of Kriya i.e., any act used to demonstrate or manifest the time quantity. It connotes the (uniform) speed with which the Musical (or Dance) event is executed over each division of the taala cycle. Such speed i.e., the rate at which elements of a Musical (or dance) event occur per unit time, is said to be first, second, third etc., depending on whether the event is executed at the initial, doubled or quadrupled rate i.e., whether the same event is executed in a given duration or in half quarter of the original duration. Thus Kala (Music speed) changes by progressive doubling.
The unit time for reckoning Kala is Matra. In order to accommodate elastic use and subjective variation, the Matra is given in Shastra a flexible definition.

1. It is equated to 'Nimeshakala' i.e., the time required to close and open the eyes naturally,
'Nimeshakalo Matrah' - Kalanidhi (commentary of Kallinatha) on Sarngadeva's Sangitaratnakara, 5.16. (Gods are called 'Animishas because they do not blink, others are 'Nimishas because their eyes open and close)
This is taken roughly equal to a second and so Matra roughly corresponds to the objective duration of a second.
2. The Matra is taken as the total duration of uttering the five short syllables 'Ka, Cha, Ta, Tha and Pa'.
3. "Pancha-Laghu - aksharocchara - mita matra" – Sarangadeva’s Sangita Ratnakara, 5.16.
This value is adopted in Marga Talas. Since Laghu (short) syllables were involved, the span was called Laghu. This also is approximately of the duration of a second.
4. In Desi Talas, however, the Laghu has a variable value; its Matra could be of 4, 5 or 6 units. This was finally standardized to a :duration of a 4 units and is so used. This Laghu is hence called Chaturashra while the one of three units is called Tisra.

==== 4.6.2 MARGA

Marga, the second mentioned of the Tala Dasa Pranas represents the actual number of aksharas taken by a kriya in terms of Talaksharas i.e., making clear the unit number of svaras for a talakshara.
Margas are of six varieties, hence termed 'Shanmargas. They are: Dakshina, vartika, Chitra, Chitratara, Chitratama, Atichitratama. There are, however, a few changes in the names in some works. A composition may have to be rendered in Madhyama laya or Vilamba Laya, yet in both the cases the akshara kalas for a kriya may be the same.

==== 4.6.3 KRIYA

The manner by which time is counted is indicated by 'Kriya'. Kriyas constitute angas. The reckoning of kriyas is done by the beating of the hands, counting by the fingers raising, and dropping of the hands to the right or left. There are two varieties of the Kriyas. They are - Sashabda kriyas and Nissabda kriyas. The former producing sound like beating the right palm on the right thigh, and the later without producing sound like counting of fingers and dropping of the palm to the side, called visarjita.
Kriyas are also divided into two kinds: Marga and Desya each admits of 8 varieties. The 8 Marga Kriyas are as follows:

==== a) Nissabda-Kriyas

1. Avapa:- Counting of the time duration by folding the fingers of the hand facing upwards.
2. Nishkrama:- Counting of the time duration by un-folding the fingers of the hand facing downwards.
3. Vikshepa: - Moving the hand towards right.
4. Pravesha: - Bringing it back.

===== b) Sashabda – Kriyas

1. Dhruva: - Producing sound with the thumb and middlefinger.
2. Shamya: - Striking on the right-hand palm with the left-hand palm.
3. Tala: - Striking on the left-hand palm with the right-hand palm.
4. Sannipata: - Clapping with both the hands facing each other.

The Desya Kriyas are as follows:

=== II. Deshya - Kriyas

===== a) Nisshabda - Kriyas:-

1. Sarpini:- Moving the hand towards left like a flag with the palm facing downwards.
2. Krishna:- Moving it towards right.
3. Padmini: - Bringing it downwards towards front side.
4. Visarjita: - Waving it outwards turning the palm upwards.
5. Vikshipta: - Bringing it towards self closing in the fingers.
6. Pataka: - Raising the hand upwards like a flag.
7. Patita: - Bringing it down like a flag.

===== b) Sashabda – Kriya

1. Dhruvaka: - A beat of the hand.

==== 4.6.4 ANGA

Anga literally means a limb or a constituent part. In tala too anga is its limb. Angas are six, known as Shadangas. They are Anudruta, Druta, laghu, Guru, Plutam and Kakapadam. Of these the first three angas are used in the Suladi Sapta talas and the remaining angas are seen in the 108 talas.

1. Anudrutam is indicated by the symbol U
2. Drutam is indicated by the symbol O
3. Laghu is indicated by the symbol I
4. Guru is indicated by the symbol S
5. Plutam is indicated by the symbol 8

Kakapadam is indicated by the symbol '+'

While Anudrutam has only one kriya and Drutam two kriyas, Laghu generally has four kriyas (beat and finger counts).
In addition, there are ten more Angas making the total Shodasangas.

The list is as follows:
[%header,format=csv]
|===
Name, Duration,No. of Kriyas In matra
Anudruta, 1, ¼
Druta, 2, ½
Druta, virama 3, ¾
Laghu, 4, 1
Laghu, virama, 5, 1½
Laghudruta, 6, 1½
Laghudruta virama, 7, 1¾
Guru, 8, 2
Guru virama, 9, 2½
Gurudruta, 10, 2½
Gurudruta virama, 11, 2¾
Pluta, 12, 3
Pluta virama, 13, 3¼
Plutadruta, 14, 3½
Plutadruda virama, 15, 3¾
Kakapada, 16, 4
|===

- 2 Laghus are equal to 1 Guru,
- 3 Laghus are equal to 1 Plutam, and '+'
- 4 Laghus are equal to 1 Kakapadm

==== 4.6.5 GRAHA
Graha denotes the place of commencement of Music in the tala avarta. Graha is basically of two kinds. When the Music commences alongwith tala, it is called the Samagraha. If the Music and tala start at different times, it is Vishama graham. This again, is of two kinds. If Music commences after the tala avarta begins, it is known as Anagata and if Music commences even before the avarta starts, it is called Atita graham. Atita graham is rarely seen in Musical compositions.
Some of the popular examples are:

1. Sama graham - Vatapi ganapatim - Dikshitar - Hamsadhwani - Adi
2. Vishama Anagata graham - Ma Janaki - Tygaraja - Kambhoji:- Adi
3. Vishama Atita graham - Apaduruku lonaitine - Adi (Javali) - Khamas

=== 4.7 SELF-ASSESSMENT QUESTIONS
Define Tala

1. Name shadangas
2. Name Sapta talas
3. Define Jati and write its vatieties
4. Name five Mahapranas

Match the following

1. Mathya tala a. One akshara kala
2. Laghuvu b. Jati
3. Graha c. 6 akshara kala
4. Trisra Jati Jhame tala d. l 0 l
5. Anu druta e. Atita