= UNIT – V 

== RAGALAKSHANAS

== 5.0 OBJECTIVES

 This unit focuses on the Ragalakshanas briefly
 The main four raga lakshanas in theory are explained here.
5.1 MAYAMALAVAGAULA
This is the 15th mela
 Aro: s r g m p d n ṡ
 Ava: ṡ n d p m g r s
 3rd raga in the 3rd chakra Agni
 ‘Agni-Go’ is the mnemonic name. The mnemonic phrases are Sa Ri Ga Ma Pa Dha nu
 Malavagaula is the original name for this raga. Maya was prefixed to the raga name, after 72 melakartha scheme.
 A murchanakaraka mela. Ri, Ma taken as shadja results in Rasikapriya and Simhendramadhyamam.
 Mela with symmetrical tetrachord separated by the interval of major tone.
 Ga and Ni are the jiva svaras. Ga and Pa are amsa svaras.
 A sarvakalika mela.
 Tristhayi raga which is free from all doshas.
 This raga evokes pathos and creates a soothing effect on the listeners.
 Bhairava Thaat of Hindusthani Music is similar to the Mayamalavagaula.
 This raga is selected to teach the fundamentals of Music to the students.
 The raga is a major raga with many janya ragas. It admits of nearly 90 janya ragas comparising of both popular and rare ragas.

===  Compositions

Gita Ravikoti Matya
Varnam Sarasijanabha Adi Swati Tirunal
Kriti Merusamana Madhyadi Thyagaraja
 Tulasidala Rupaka Thyagaraja
 Vidulaku Adi Thyagaraja
 Rakshimpave Jhampe Thyagaraja
 Devi Sri Tulasamma Adi Thyagaraja
 Srinadadi Adi Muthuswamy Dikshitar
 Mayatita Rupaka Ponnayya
 Devadeva Rupaka Swati Tirunal
 Kshirasagara Dhruva Jayachamaraja Wodayar
 Adikondar Adi Muthutandavar
 Devadideva Adi Mysore Sadasiva Rao
 Sharmaprada Rupaka Thulaseevanam
 Adityan Devadidevam Adi Muthaiah Bhagavathar
 Taraka nama Adi Muthaiah Bhagavathar
 Mahima Ariya Adi Papanasam Sivan
 Bhuvaneswari Desadi Papanasam Sivan
 Illathathai Adi Papanasam Sivan
 Nenerumganu Adi Pallavi Seshayyar
 Mayam Edo Adi Papanasam Sivam
 Chintayesham Rupaka Vasudevachar
 Kalinarulokunimahima Adi Mysore Vasudevachar
 Hari Bittare Adi Purandaradasu

== 5.2 MALAHARI

 A janya raga derived from the 15th melakarta Mayamalavagaula
 Arohana: s r m p d ṡ
 Avarohana: ṡ d p m g r s
 Besides Shadja and Panchama, the notes taken are suddha rishabha,antara gandhara,suddha madhyama and suddha daivata
 Audava –shadava raga.
Varja raga.the notes ga and Ni are deleted in arohana .the note nishada is deleted in avarohana nishada varja raga.
 Upanga raga.
 Ma, pa and dha are jiva svaras.
 A moring raga.it is a raga free from all doshas or evils and it is very appropriate that the first compositions that the students learn after their preliminary svara exercises in Mayamalavagaula are the pillari gitas of Purandara dasa in this raga.
 This raga name has undergone changes like Malahara, Malhari, Malhar and Mallar. Malahari literally means that which removes dirt. Malahari is a raga ascribed to the rainy season and when rain fall, all dirt is removed from buildings ,roads and atmosphere. Malahari cleanse the mind of all evil thoughts and Purandara dasa’s Pillari gitas are appropriately composed in this raga.
 Compositions begin on the notes ri, ma, pa, and dha. Tristhayi raga.this is a minor raga and does not give scope for elaborate alapana.
 This raga is mentioned in the following works.
1. Sangita Makaranda of Narada.
2. Sangita Ratnakara of Sarangadeva
3. Sangitachudamani of Jagadeka malla
4. Panditaradhya charitra of Palkuriki Somanatha Kavi
5. Sangitasara of Vidyaranya
6. Songs of Annamacharya of Tirupati
7. Chaturdandi prakasika of Venkatamakhi
8. Ragatala chintamani of Poruri Govindakavi
Compositions
Gita Srigananatha Roopaka Purandara dasa
Gita Kundagaura Roopaka Purandara dasa
Gita kereyaneeranu Triputa Purandara dasa
 Padumanabha Triputa Purandara dasa
Kriti Panchamatanga Roopaka Muttuswamy Dikshitar

== 5.3 MOHANA

 A popular Janya raga; derived from the 28th melakarta, Hari Kambhoji.
 Arohana : s r g p d ṡ
 Avarohana : ṡ d p g r s
 This is a sarva svara murchanakaraka janya raga
 ri as shadja gives Madhyamavati
 Ga as shadja gives Hindolam
 Pa as shadja gives Suddha saveri
 Dha as shadja gives Udayaravichandrika.
 Besides Shadja and Panchama, the notes taken are : the Chatussruti Rishabha, Antara Gandhara and Chatussruti Dhaivata.
 Audava raga; varja raga; the notes ma and ni are deleted,
 Symmetrical raga.
 Upanga raga,
 ri,ga and dha are the raga chhaya svaras;
 ga and pa are amsa svaras i.e. resting notes.
 Janta svara prayogas g g p p d d ṡ ṡ and datu svara prayogas like d ġ ṙ ṡ d p , d ṙ ṡ d p g d p g r and r p g r s are prominent.
 Sarva svara gamaka varika rakti raga.
 One of the major ragas and gives scope for elaborate alapana.
 Can be sung at all times; but still night time is best suited for this raga.
A raga capable of evoking more than one rasa. All types of compositions are represented in this raga. This raga figures in operas and dance dramas. It is useful for singing themes relating to varnana or description.
 An auspicious raga. Mangalams have been composed in this raga.
 Compositions in this raga commence on the notes sa, ga and dha.
 Mohana corresponds to the Bhup (Bhupali) of Hindustani Music.
 A raga useful for being sung at the commencement of concerts.
Some prominent compositions
Gita Varavina Rupaka Ancient
Svarajati Samidayamira Adi Ancient
Varna Ninne kori Adi Pallavi Duraisami Ayyar
Varna Ninnukori Adi Ramnad Srinivasa Ayyangar
Varna Sarasijakshi Ata Vina Kuppayyar
Pada Varna Sariga dani Adi Karvetinagar Govindasamayya
Kriti Bhavanuta Adi Tyagaraja
Kriti Nanu palimpa Adi Tyagaraja
Kriti Mohanarama Adi Tyagaraja
Kriti Enduko baga Adi Tyagaraja
Kriti Rama nine Adi Tyagaraja
Kriti Evarura Chapu Tyagaraja
Kriti Maruvakudaya Adi Karur Dakshinamurti Sastri.
Kriti Nenarunchara Adi Karigiri Rao
Kriti Peddadevudani Adi Mysore Sadasiva Rao
Kriti Bhuvanatraya Adi GN Balasubramanyam
Kriti Sadapalaya Adi GN Balasubramanyam
Kriti Bhadrakali namostute Adi Muttayya bhagavatar
Kriti Rara rajiva lochana Adi Mysore vasudevachari
Kriti Chintaye padmanabham chapu Swati tirunal
Kriti Mohanam tava Adi Swati tirunal
Kriti Pari pahimam Chapu Swati tirunal
Kriti Chintayamyaham Adi Ambujam Krishna

== 5.4 KALYANI

 65th melakarta raga ; sampoorna raga
 The most popular and well-known prati-madhayama raga
 Arohana : s r g m p d n ṡ
 Avarohana : ṡ n d p m g r s
 Besides Shadja and Panchama, this raga takes the Chatussruti Rishabha, Antara Gandhara, Prati Madhyama, Chatussruti Dhaivata and Kakali Nishada
 to conform to the Katapayadi formula, the phrase ‘Mecha’ was prefixed to the name of this raga
 5th raga in the XI charka; Rudra-ma
 A melakarta claiming a large number of janya raga. In the obsolete nomenclature for the 72 melas, the 65the mela is named Santakalyani.
 Ri gu mi dhi nu- are the Svara mnemonics
 This is a murchchanakaraka mela, Its ri, ga, pa, dha and ni taken as shadja, respectively result in the ragas, Harikambhoji, Nathabalravi, Sankarabharana, Kharaharapriya and Todi.
 Sarva svara gamaka varika rakti raga. In both the arohana and avarohana, all the Svaras are ragachhaya Svaras.
 Ri, ga, dha and ni are nyasa svaras :
 ga and pa are resting notes.
Janta svara prayogas like r r g g m m dd. g g m m d d n n, m m d d n n r r and datu svara prayogas like n g’ ṙ n, d n ṙ n d m, g n d m g r are prominent.
 Madhyama varja phrases like g g d d n n ṙ ṙ lend beauty to the raga. The phrase D n r g m d n ṙ n d m g r n where both shadja and panchama notes are deleted, adds beauty to the raga
 Gamakas of the kampita, Sphuritam and Tripuchcham variety lend colour to this raga.
 A majestic raga. One of the major ragas and affords scope for elaborate alapana.
 Well distributed.
 Can be sung at all times; but the effect is decidedly better when sung in the evening.
 On account of the presence of tivra svaras in this raga, it is very useful for being sung at the commencement of concerts. The requisite Musical atmosphere is soon created.
 All great composers and minor composers of note have composed in this raga.
 All types of compositions are represented in this raga. Useful for singing slokas, padyas and viruttams. Figures in operas and dance dramas.
 Compositions in this raga begin on the notes, sa, ri, ga, pa, and ni. The scale of Kalyani (Yaman that of Hindusthani Music) is met within Hungarian Music.
 This is the earliest prati madhyama raga known to Musical history and is the ga murchhana of shadja grama.
 Subtle srutis like tivra antara gandhara 81/64 and tivra kakali nishada 243/128 figure in some places.
Some Prominent compositions:
Gita Kamalajadala Triputa Ancient
Varna Vanajakshiro Adi “
Varna Vanajaksha Ata Pallavi Gopalayyar
Kriti Nidhi chala Chapu Tyagaraja
Kriti Etavunara Adi Tyagaraja
Kriti Sive pahimam Adi Tyagaraja
Kriti Nammi vachchina
(Kovur Pancharatnam) Adi Tyagaraja
Kriti Bhajana Sayave Adi Tyagaraja
Kriti Evara madugudura Adi Tyagaraja
Kriti Sundari ni divya
(Tiruvottiyur
Pancharatnam) Adi Tyagaraja
Kriti Amma ravamma Jhampa Tyagaraja
Prahlada Bhakti Vijayam (Opera) Vasudevayani Adi Pallavi Gopalayyar Tyagaraja
Kriti Kamalambam Adi Muttuswamy
Dikshitar
Kriti Bhajarere Chapu Muttuswamy
Dikshitar
Kriti Talli ninnu nera Misrachapu Syama Sastri
Kriti Biranavara lichchi Rupaka Syama Sastri
Kriti Himadrisute Rupaka Syama Sastri
Kriti Ninnu vina gati gana Adi Subbaraya Sastri
Kriti Birana brova Rupaka Talangambadi Panchanadayya
Kriti Nija dasa varada Adi Patnam Subrahmanya Ayyar
Kriti Aviralamagu Triputa Cheyyur
Chengalvaraya Sastri
Kriti Saraswati Rupaka Tiruvottiyur Tyagayyar
Javali Entati Kuluke Rupaka Pattabhiramayya 


== 5.5     SANKARABHARANAM


 This is the most popular scale in all the systems of the whole world.
 Sampoorna raga.
 This is a 29th mela (V-5 Bana – ma). ‘Dhira’ is added to suit the Katapayadi formula
 The Svaras used are Shadja, Chatusruti Rishabha, Antara Gandhara, Suddha Madhyama, Chatusruti Dhaivata and Kakali Nishada.
 Arohana : s r g m p d n ṡ
 Avarohana : ṡ n d p m g r s
 Sankarabharana is called Major Diatonic Scale in the Western Music. Scholars say that the dhaivata in the Major Diatonic scale is Trisruti Dhaivata.
 Sankarabharana was mentioned in Sangita Makaranda,
Sangita Ratnakara and other treatises. This was mentioned as Purna Prasiddha Raganga Raga by Sarngadeva and as Napumsaka raga by Narada
 Vidyaranya mentioned it as one in his 15 melas and Lochana Kavi considers Sankarabharana as one of the 12 thats in his Ragatarangini. Sankarabharana was mentioned as the 29th mela by Venkatamakhi
 Bilaval’ is the equivalent Hindustani raga for Sankarabharana.
 The r- d and g – n are samvadis. Similarly s –r and p-d are in Purna Chatusruti gap. This was considered as the nishada murchana – ‘Ranjani’ of the ancient shadja grama.
 In Tamil Music, ‘Sambalai’ is the equivalent of Sankarabharana, Pazhvalam Panjaram is again Sankarabharana
 mid – day raga
 s,ri,gu,ma,p,dhi,nu – are the Svara mnemonics.
 Madhyama is used in different ways in Sankarabharana.
Kakali Nishada is sung in slightly higher frequency.
 ṡ N p – ṡ D p m g – s D p m g – g m r G – are some of the ranjaka prayogas. d g – d r are avoided as they are more frequently used and more suitable to Kalyani.
 Sankarabharana is a sarva Svara gamaka varika rakti raga. Gandhra is sung without oscillations. Ri and Dha are kampita Svaras. They are sung in higher intensity than Purna Chatusruti. Long dirgha and kampita Ri and Dha are characteristic notes for Sankarabharana.
 Apart from s and p, Gandhara is a good nyasa Svara. Dhivata is not a nyasa Svara. Janta Svara prayogas are suitable in this raga.
 ṙ n ṡ d n p d m p g m r g s – is a good datu Svara praya. There is western (Music) influence found in the ‘Chalamela’ – Ata tala varna of Swati Tirunal.
 Tristhayi raga. Sarvakalika raga. Gives scope for elaborate alapana. Suitable for all times and all varieties of Musical compositions. Very popular rakti raga.
 This is a PanchaSvara – murchankaraka mela.
r – Kharaharapriya g – Hanumattodi m – Mechakalyani p – Harikambhoji
d – Nathabhairavi

==== Some Compositions

Gita Arere Simhannadana Ancient
Varna Sami nine Adi Karur Dakahina Murti
Varna Chalamela Ata Swati Tirunal
Kriti I Varaku Rupaka Tyagaraja
Kriti Manasu
Swadhinamaina Tirputa Tyagaraja
Kriti Emineramu Triputa Tyagaraja
Kriti Eduta nilichite Adi Tyagaraja
Kriti Enduku Peddala Adi Tyagaraja
Kriti Svaragasudharasa Adi Tyagaraja
Kriti Buddhi radu Adi Tyagaraja
Kriti Sarojadalanetri Adi Syamasastri
Kriti Devi Minanetri Adi Syamasastri
Kriti Akshayalingavibho Chapu Muttuswamy
Diskhitar
Kriti Sri Dakshinamurte Mishra Jhampe Muttuswamy
Diskhitar
Kriti Kamalamba
Navavaranakriti Rupaka Muttuswamy
Diskhitar
Kriti Nagalingam Bhajeham Rupaka Muttuswamy
Diskhitar
Kriti Sadasivam Upasmahe Adi Muttuswamy
Diskhitar
Kriti Devi Jagajjanani (Navaratri Kriti) Adi Swati Tirunal
Kriti Begumiraganu
(Sri Venkatasa
Pancharatna Kriti) Rupaka Vina Kuppayyar
Kriti Evvade Triputa Kshetrayya

=== 5.6 SELF-ASSESSMENT QUESTIONS
1. Write the ragalakshanas of Mohana Raga
2. Write some rachanas in Sankarabharana raga
3. Write the ragalakshanas of Malahari
4. Write some examples in Kalyani raga
5. Name some prominent compositions in Mayamalavagaula
raga