:linkcss:
:imagesdir: ./images
:stylesdir: stylesheets/
:stylesheet:  colony.css
:data-uri:



== 1. 	SREE GANANATHA

Ragam: Malahari 
ARO:   	s r1 m1 p d1 ṡ || 
AVA:  	ṡ d1 p m1 g3 r1 s 	|| 
Talam: Rupakam (Chathurasra Jathi)

==== Composer: Purandaradasa
==== Sahityam:
Sri Gananatha Sindhoora Varna Karuna Saagara Kari Vadana 
Lambodhara Lakumi-karaa Ambaa Sutha Amara Vinutha 
Siddha Chaarana Gana Sevitha Siddhi Vinayaka Te Namo Namo 
Sakala Vidyaadi Poojitha Sarvothama Te Namo Namo

1. 
m 	p    | d ṡ ṡ 	 ṙ    || ṙ 	 ṡ      | 	d 	p 	m p     ||  
Sree -  | Ga na na tha ||   sin dhu | 
 	- 	ra var na  ||  
r 	m  | p d m 	p || 	d 	p 	| 	m 	g 	r s    ||  
Ka 	ru | na Sa ga ra || 	ka ri 	| 	va  dha - na  ||  
 
s 	 r  | m , 	g 	r || 	s 	r 	| g	r 	s , ||
Lam -  | bo - 	dha ra || 	la 	ku 	| mi ka ra - || 
 
r	m  | p d m 	p    || 	d 	p 	| m 	g 	r  s   || 
Am -  | ba - 	su tha   || 	a 	ma | ra vi 	nu  tha|| 
 
s	r  | m , 	g 	r || 	s 	r 	| g 	r 	s , || 
Lam -  | bo - 	dha ra || 	la 	ku 	| mi ka ra - || 
 2. 
m 	p     | 	d ṡ 	ṡ ṙ    ||  ṙ 	 ṡ 	|d   p  m    p  ||  
Sid dha   | cha - 	ra na   || ga na 	|se - 	vi  tha || 	 
 
r m     |p d m p   || d p | m g r    s   ||  Sid dhi  |vi na ya ka   || the - | na mo na  mo||  
 	    	 	 	 	  	 	 	 	 	 	  	(Lam) 
3. 
m 	p     | 	d ṡ 	ṡ ṙ || ṙ 	ṡ 	| d 	p 	m p || 	 
Sa 	ka  | 	la vi 	dya - 	|| - 	dhi | 	pu - ji  tha 	|| 	 
 
r 	m  | p d m 	p || 	d 	p 	| m 	g 	r s || 	 
Sa 	-  | rvo - 	tha ma || 	the - 	| na mo na  mo 	|| 	 
 	    	 	 	 	  	 	 	 	 	 	  	(Lam) 
 
=== LESSON VII
==== 2. KUNDA GAURA

: Malahari    
	Arohanam : s r1 m1 pd1 ṡ  	 	 
 	Avarohanam: ṡ d1 pm1 g2 r1 s                             
Talam:  Rupakam   (Chathurasra Jathi) 
Composer: Purandaradasa 
 
==== Sahityam:

Kunda goura Gowri vara mandhirãya

mana makuta mandãra kusumãkara makarandam vãsithuvã

Hé makuta simhãsana virupãksha karunãkara (Man) 

Chanda mãma mandãkini mandirãya mãna makuta (Man) 
 
1. 
d 	p   |   m     g  r    s    || 	r 	m 	| 	p 	d  m 	p   || 
Kun da |   Gau - 	- ra ||  Gau - 	| 	Ri - va ra || 
 				
d 	ṙ | ṙ  	ṡ 	d 	p || 		d 	p 	| 	m 	g    r  s || 
Man di | -  
 	ra - 	ya || 	ma - 	| 	na ma ku ta || 
s 	, | r  	, 	r 	, || 		d 	p 	| 	m 	g r   s    || 
Man - | da 	- 	ra 	- || 	ku su 	| 	ma - ka ra|| 
 
	s 	r | m 	, 	g 	r || 	s 	r 	| g 	r s , || 
	Ma ka | ran - 	dam - || 	va - 	| si 	thu va - || 
 2. 
	d 	p | m 	 	g 	r s || 	r 	m 	| p 	d  m 	p || 
	He 	ma | ku - 	- 	ta || 	sim - 	| ha - sa na|| 
 
	d 	ṙ | ṙ  	ṡ 	d 	p    || 	d 	p 	| m 	g  r  s  || 
	Vi 	ru| pa 	ra - 	ksha|| 	ka ru 	| na - ka ra|| 
	 	    	 	 	 	  	 	 	 	 	 	 (Man) 
 3. 
	d 	p | m 	 	g 	r s || 	r 	m 	| p 	d  m 	p  || 
	Chan da | 	ma - 	- ma|| man  - 	| da - gi 	ni|| 
 
	d 	ṙ | ṙ  	ṡ 	d 	p || 	d 	p 	| m 	g    r  s|| 
	Man - | di 	 	ra - ya || 	ma - 	| na 	ma ku ta|| 


=== LESSON VIII

=== 3. KERAYA NEERANU
: Malahari  
ARO:  s r1 m1 pd1 ṡ 	||  	AVA: ṡ d1 pm1 g2 r1 s 	|| 
Talam:  Triputa    (Chathurasra Jathi) 
Composer: Purandaradasa 
 
Sahityam: 
Kereya Neeranu Kere ge Jalli Varava Padedava Rante Kaanero! 
Hari ya Karunada laada Bhagyava Hari Samarpane Maadi Badukiro Shree Purandara Vittala Raayana Charana Kamalava Nodi Badukiro  
1. 
d 	ṡ  ṡ 	| d 	p | m  p || 	d d 	p | m m |p  p || 
Ke 	re  ya | Nee - | ra 	nu|| 	Ke re 	ge | chal -|li  - || 
 
d d  ṡ | d p | m p || d d p |m   g   | r s || Va ra  va | pa de | da va || ran - te |Kaa - | ni ro || 
 
s 	r  r 	| s 	r | s 	r || 	d d 	p |m    g  | r  s || 
Ha ri  ya | ka ru | na 	do|| 	laa - 	da |bha - |gya  va|| 
 
d 	p  d 	| ṡ 	- | d 	p || 	d d 	p | m g | r s || 
Ha ri  sa | ma - | rpa ne|| 	ma - 	di | ba du | ki ro|| s r  r | s r | s r     || d d p | m g | r s || Ha ri  ya | ka ru | na da || la - ya | bha -|gya va|| 
2. 
	d 	ṡ  ṡ 	| d 	p | m  p || 	d d 	p | m m | p  p || 
	Sree -  pu | ran - | da 	ra || 	vi ta 	la | ra - | ya - || 
 
	d 	d  ṡ 	| d 	p | m 	p || 	d d 	p | m g | r s || 
	Cha ra  na | ka ma | 	la va || 	no - 	di | ba du | ki ro|| 
 
s r  r | s r | s    r  || d d p |m   g  | r s || Ha ri  ya | ka ru | na  do|| la - da |bha -|gya va || 
 
	d 	p  d 	| ṡ 	, | d 	p || 	d d 	p | m g |r  s || 
	Ha ri  sa | ma - | rpa ne|| 	ma - 	di | ba du |ki ro ||

==== LESSON IX
=== 4. PADUMANABHA

Malahari (15th Melakartha Janyam)
ARO: s r1 m1 pd1 ṡ || 
 	AVA: ṡ d1 pm1 g2 r1 s 	|| 
Talam:  Triputa    (Chathurasra Jathi) 
 
Sahityam: 
Padumanaabha Parama Purushaa Param Jyoti Swaroopaa 
Vidhura Vandya Vimala Charita Vihanga Adirohana 
 
Udadhi Nivaasa Uraga Shayana Unnatonnata Mahima  
Yadukulottama Yagnya Rakshaka Yagnya Shikshaka Raama Naama 
 
Vibheeshana Paalaka Namo Namo Ibha Varadaayaka Namo Namo 
Shubha Prada Sumanorada Surendra Manoranjanaa Abhinava 
Purandara Vithala Bhallare Raama Naama 
 
r	s  ḍ 	| s 	, | s 	, || 	m g 	r 	| m m | p , || 
Pa 	du ma | na - | bha - || 	pa ra ma | pu ru |sha - || 
 
s	d  , | d p | m p || d d p | m g | r s || Pa ram - | jo - | - ti || sva ru - | pa - | - - || r 	s  ḍ 	| s 	, | s 	, || 	m g 	r 	|m     m | p , || 
	Vi 	du ra | van - | dhia - || 	vi ma la |cha ri | ta - || 
s d  , | d p | m p || d d p | m g | r s || Vi hang - | ga - | - di || ro - ha | na - | - - || 
 
2. 
 
	p 	m  p 	| d ṡ | d 	ṡ || 	ṙ ṡ 	d | d ṡ |d   p || 
	U 	dha dhi | ni 	va | - 	sa || 	u ra ga | sa ya |-  na|| 
 
d d  p | p , | p m || r m m | p   , | p , || U -  nna | to - | nna ta || ma hi - | ma   - | - - || 
 
	d 	d  p 	| p 	, | p 	m || 	r 	, 	m | m g| r      s || 
	Ya 	du ku | lo 	- | ttha ma || 	ye - 	gna | ra -|ksha  ka || 
 
	s 	,  s 	| d 	d | d 	p || 	p , 	p | m g |r s || 
	A 	-  gna | si 	- | ksha ka || 	ra - 	ma | na - |- ma || 
	 	    	 	 	 	  	   	 	 	 	 	 	(Paduma) 
 3. 
	d 	ṡ     , | d 	p | m 	p ||d 	d p| m g 	| r s || 
	Vi 	bhee   - | sha na | pa 	- ||la 	ka -| na mo  | na mo|| 
 
 
ṙ 	ṡ  , 	| d 	p | m 	p || 	d d 	p |m    g  | r s || 
I 	bha - 	| va ra | da 	- || 	ya ka - 	|na  mo| na mo|| 
 
p 	m  p 	| d ṡ | d 	ṡ || 	ṙ ṡ 	d | d ṡ |d  p || 
Su 	bha - 	| Pra da | Su 	ma || 	no - 	ra | da - |- Su || 
 
d 	d  p 	  | p 	, | p 	m ||  r 	, 	m 	| 	p    ,  | ,    ,  || 
Re 	-  ndra  | Ma - | no 	- ||ran - 	ja 	| 	na - | - -  || 
 
d 	d  p   | p , 	| p m 	|| r 	, 	m 	| 	m g | r s || 
A 	bhi -   | na - 	| va pu 	|| ran - 	da | 	ra - | - vi || 
 	  
s ,  s | d d | d p || p , p |  m g |  r s || tal -  la | bhal - | la re || ra - ma | na - |- ma || 

=== LESSON X
==== 5. VARAVEENA
: Mohanam  (28th melakartha janyam) 
	Arohanam : s r2 g2 pd2 ṡ  	 	 	 	 
Avarohanam: ṡ d2 pg2 r2 s 
Talam:  Rupakam ( Chaturasra Jati) 
 
Sahityam: 
Varaveena Mrudu Paani Vanaruha Lochana Raani 
Suruchira Bambhara Veni Suranuta Kalyaani  
Nirupama Shubha Guna Lola Niratishaya Prada Sheela 
Varadaapriya Ranganaayaki Vaanchita Phala Daayaki 
Saraseejasana Janani Jaya Jaya Jaya Jaya rere 
 
	g 	g      | p , 	p  , 	| d        p   || ṡ 	, ṡ ,  	|| 
	Va        ra  | vee - 	na       -  | Mru     du   || Pa      - ni    -      || 
 
	ṙ 	ṡ      | d d 	p     , 	| d        p     || 	g 	g r ,   || 
	Va     na    |  ru      ha 	Lo   - | cha      na     ||  Raa      - ni   -    || 
 
	g 	p      | d ṡ 	d   , 	| d       p     || 	g 	g r ,  	|| 
Su     ru    | chi ra Bam - 	| bha      ra     || 	Ve   - ni    -      || g 	g      |  d p 	g     , 	| p       g 	    || 	g 	r s ,  	|| 
Su 	 ra     | nu tha Kal    -    | ya         -        || 	-       - ni     -     || 
 
g 	g      | g 	g 	r  g 	| p           g     || 	 p , p ,  	|| 
Ni     ru      | pa ma Shu bha  | Gu         na    || 	 Lo   - la    -       || 
 
g 	g      | d p 	d     , 	| d            p     || 	  ṡ , ṡ ,  	|| 
Ni        ra    | ti Ja ya     -     | Pra         da   || 	See   - la    -     || 
 
d 	ġ      | ṙ 	ṙ 	ṡ  ṡ 	| d       ṡ     || 	 d d d p    || 
Va       ra   | da - 	Pri    ya    | Ran    ga  ||  naa    - 	ya    ki    || 
 
g p      | d ṡ d  p | d         p     ||  g   g   r    s || Vaa    -      | nchitha Pha la | Daa      -     || -     - ya    ki || 
 
s 	r      | g 	, 	g  , 	| g         r 	    || 	p g r , || 
Sa     ra     | si - 	ja     -     | sa        na     ||   na 	ni    -      || 
 
s 	r      | s 	g 	r  s 	|| r 	r 	| 	s 	d s, || 
Ja    ya     | 	ja ya ja     ya 	|| jaya re , re . || 

=== LESSON XI
=== 6. ANALEKARA
: Suddha Saveri (29th mela janyam) 
	Arohanam : s r2 m1 pd2 ṡ 	 	 	 	 	 
Avarohanam: ṡ d2 pm1 r2 s 
Talam:  Triputa   (Thisra Jathi) 
 
Sahityam: 
Aanalekara Unni Poladi Sakala Shaastrapuraana 
Dheenam Taala Dheenam Taala Parigathu Rere  
Setu Vaaha Pariga Tamnam Jataajoota 
 
	ṙ 	ṁ   ṙ 	| ṙ 	ṡ | d 	ṡ || 	ṡ 	, 	ṡ 	| d p |m   p || 
	A 	-  na | le 	- | ka 	ra || 	un - 	ni | po - |la   di || 
 
	d 	d  ṡ 	| d 	, | d 	p ||p  m  r   |d d | d p || 
	sa    ka      la | sha -    |sthrapu|| ra  - na  |di - 	| nam - || 
 
p ,  p | d d | d p ||p , p | m p |d     p    || tha -  la | di - | nam - ||tha - la | pa ri |ga    thu || 
 
p m  r  | s r | s r ||p m p | s r     |  s     r re -    re     | a - | - - ||a - -      | a -      | - - || p p  d | p p | m r ||     r s   r | m , | m , || a -      - | a - | - - ||    se - thu | va - | ha - || 
 
d 	p  d     |  ṡ 	, | ṡ 	, || 	ṙ 	ṙ 	ṡ 	| d p |m 	p || 
pa 	ri  ga |tham - | nam - || 	ja ta 	- 	| ju - | -    ta || 
 
d 	d  ṡ 	| d 	, | d 	p || 	p m 	r 	| d d | d p || 
sa 	ka la 	| sha - | sthrapu|| 	ra - 	na | di - |nam - || 
 
p 	,  p 	| d 	d | d 	p || 	p , 	p | m p | d 	p || 
Tha -  la 	| di 	- | nam - || 	ta - 	la | pa ri | ga  tu || 
 	   	 	 	 	  	   	 	 	 	 	 	 	 
p 	m  r 	| s 	r | s 	r || 	p m 	p | s r | s r || re 	-      re | a 	- | - 	- || 	a 	- 	- 	| a - | a - || 
 
p 	p  d 	| p 	p | m 	r || 	r 	s 	r 	| m , | m , || 
a 	-      - 	| a 	- | - 	- || 	se - 	thu | va - | ha - || 
 
d p  d     |     ṡ     ,     | ṡ   ,   ||  pa ri      ga | tam   - |    nam  - || LESSON XII 

=== SVARAPALLAVI
Vasanta

Aarohana:  s g m d n ṡ     
	  	Avarohana: ṡ n d m g r s 
Talam: Misra Chapu 
 
Pallavi: 
ṡ , , , , n , || d , , , , m , || g , , , , r , || s , , , , s ṇ || ḍ  ṇ  s  g  m  d  n || 
Charanam 1: 
ṡ , , , , n , || d , , , ,  n , || m , , , , d ,  || g , , , , m , || s , , , , ṇ , || s , , , ,  g , || m , , , , d n  ||(s …) Charanam 2: 
ṡ , n  d  m  d  n  || d , m g  m  d  m || g , m  g  r  s ṇ  || ḍ , ṇ  ḍ  ṃ ḍ  ṇ || s , ṇ  s  g  m  d  || m ,  n d m  d  n  || (s…) 
Charanam 3: 
ṡ n ṡ d  n  ṡ  m || d  n ṡ g  m  d  n  || ṡ ṇ s g  m  d  n   || ṡ n  d m  d  ,  n ||(s…) 
Charanam 4: 
ṡ  ġ ṁ  ġ  ṙ ṡ  n  || d  n  ṡ  n  d  m  g  || m  d  n ṡ  n  d  m ||  g  m  d  m  g  r s  
|| ṇ  s  ṇ  ḍ  ṇ  s  g  || m  d  m  g  m  d  n || ṡ  ġ ṁ  ġ  ṙ ṡ  n ṙ  ṡ || n  d m  d  n 
|| (s . . ) 

=== REFERENCE BOOKS

1.	South Indian Music - 3 volumes by Prof P.Sambamurthy 
2.	Sangeetha Sastra Samgrahanam by P.K. Indrani 
3.	Ganamrutha Bodhini by A.S. Panchapakesa Iyer. 
4.	Sangeetha Vidya Prakasika by Aakondi Srinivasa RajaRao 
5.	http://beautifulnote.com/blog/2010/04/07/carnatic-musictheory-download.html 
